# Meta Data for SEO

title: "Gatling"
titleSeparator: "-"
description: "Documentation"
logos:
  white: "/images/logo-gatling.svg"
  black: "/images/logo-gatling-noir.svg"

## Open Graph + Twitter Cards
images: ["images/og-gatling.png"]
twitterSite: "GatlingTool"
twitterCreator: "GatlingTool"
facebookAuthor: "GatlingTool"
facebookPublisher: "GatlingTool"
ogLocale: "en_US"

## JSON-LD
schemaName: "Gatling Corp"
schemaLogo: "gatling-logo.png"
schemaTwitter: "https://twitter.com/GatlingTool"
schemaLinkedIn: "https://www.linkedin.com/company/gatling/"
schemaGitHub: https://github.com/gatling

## Sitelinks Search Box
siteLinksSearchBox: false

## Chrome Browser
themeColor: "#fff"

# Images
quality: 85
bgColor: "#fff"
lqipWidth: "20x"

# Footer
footer: ""

# Alert
alert: false
alertText: ""

# Edit Page
editPage: true

includeCode:
  default: java
  labels:
    java: Java
    kt: Kotlin
    scala: Scala
