# Meta Data for SEO
title: "Gatling Documentation"
titleSeparator: "-"
description: "Documentation"

## Open Graph + Twitter Cards
images: ["images/og-gatling.png"]
twitterSite: "GatlingTool"
twitterCreator: "GatlingTool"
facebookAuthor: "GatlingTool"
facebookPublisher: "GatlingTool"
ogLocale: "en_US"

# Header
logos:
  white: "images/logo-gatling.svg"
  black: "images/logo-gatling-noir.svg"

## JSON-LD
schemaName: "Gatling Corp"
schemaLogo: "images/og-gatling.png"
schemaTwitter: "https://twitter.com/GatlingTool"
schemaLinkedIn: "https://www.linkedin.com/company/gatling/"
schemaGitHub: https://github.com/gatling
schemaSection: tutorials

## Sitelinks Search Box
siteLinksSearchBox: false

## Chrome Browser
themeColor: "#fff"

# Images
quality: 85
bgColor: "#fff"
lqipWidth: "20x"

# Alert
alert: false
alertText: ""

# Edit Page
editPage: true

includeCode:
  default: java
  labels:
    java: Java
    kt: Kotlin
    scala: Scala
