language: scala
jdk:
  - oraclejdk8
sbt_args: -Xmx2048M
before_script: ./make_credentials.sh
script: 
  - sbt test
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
  - "[[ $TRAVIS_PULL_REQUEST == \"false\" ]] && sbt publish || true"

# If building master, Publish to Sonatype and trigger builds
after_success:
  - "[[ $TRAVIS_PULL_REQUEST == \"false\" ]] && ./trigger_build.py gatling/gatling-highcharts"
  - "[[ $TRAVIS_PULL_REQUEST == \"false\" ]] && ./trigger_build.py gatling/gatling-vtd"
  - "[[ $TRAVIS_PULL_REQUEST == \"false\" ]] && ./trigger_build.py gatling/gatling-maven"
  - "[[ $TRAVIS_PULL_REQUEST == \"false\" ]] && ./trigger_build.py gatling/gatling-sbt"

sudo: false

# Cache settings
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/launchers

# whitelist
branches:
  only:
    - master
