language: scala
jdk:
  - openjdk8
sbt_args: -Xmx2048M
before_script: ./make_credentials.sh
script: 
  - sbt ci-checks
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm || true
  - "[[ $TRAVIS_PULL_REQUEST == \"false\" ]] && sbt publishLocal || true"

sudo: false

# Cache settings
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/launchers

# whitelist
branches:
  only:
    - master
